language: php

sudo: false

env:
    - psalm="yes" psalmflags="--taint-analysis"

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly
    include:
        - php: 7.0
          env:
            - psalm="no"

install:
    - travis_retry composer install --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-text
    - - if [[ "$coverage" = "yes" ]]; then ./vendor/bin/psalm $psalmflags; fi

cache:
    directories:
        - vendor
        - $HOME/.cache/composer
